/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: mediochrea (https://sketchfab.com/mediochrea)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/mozilla-hubs-challenge-wizards-library-36ce7f88393749caaed5d8b700f7b5d1
title: Mozilla Hubs Challenge - Wizard’s Library
*/
import React, { useEffect } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";

export default function BaseContainer({ ...props }) {
  const { scene, animations } = useGLTF('/world.gltf');
  const { ref, actions } = useAnimations(animations);

  useEffect(() => {
    /*--- Play object default animation --*/
    actions["Take 001"].play();
  }, [actions]);

  return <primitive object={scene} {...props} ref={ref} />;
}

useGLTF.preload('/world.gltf')
