/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Anthony Yanez (https://sketchfab.com/paulyanez)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/crystal-ball-23e1b3d8c0f843e0960c673d932712f2
title: Crystal Ball
*/
import * as THREE from "three";
import React, { useEffect, useState } from "react";
import { useGLTF, useAnimations, useCursor } from "@react-three/drei";

export default function Model({ v = new THREE.Vector3(), ...props }) {
  const { scene, animations } = useGLTF("/crystal.gltf");
  const { ref, actions } = useAnimations(animations);
  const [active, setActive] = useState(false);

  useCursor(active);

  useEffect(() => {
    actions["Take 001"].play();
  }, [actions]);

  return (
    <primitive
      object={scene}
      {...props}
      ref={ref}
      onPointerOver={() => setActive(true)}
      onPointerOut={() => setActive(false)}
    />
  );
}

useGLTF.preload("/crystal.gltf");
