/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Guillermo T (https://sketchfab.com/guillermot)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/fire-c678d3cb21a94cd38e52abb50a503c40
title: Fire
*/
import React from "react";
import { useGLTF } from "@react-three/drei";

const Fireball = React.forwardRef( (props, ref) =>  {
  return <primitive object={props.scene} ref={ref} scale={props.scale} position={props.position}/>;
});

export default Fireball;

useGLTF.preload('/fireball.gltf')
